-- Supabase Schema for Bloom Cycle Tracker

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  partner_name TEXT DEFAULT 'My Girlfriend',
  user_name TEXT DEFAULT 'Partner',
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Cycles Table
CREATE TABLE IF NOT EXISTS cycles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  flow_intensity JSONB DEFAULT '{}'::jsonb,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Daily Logs Table
CREATE TABLE IF NOT EXISTS daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  symptoms JSONB DEFAULT '[]'::jsonb,
  mood_tags JSONB DEFAULT '[]'::jsonb,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT daily_logs_user_date_unique UNIQUE (user_id, date)
);

-- 4. Create Reminders Table
CREATE TABLE IF NOT EXISTS reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  recurrence_rule TEXT NOT NULL,
  phase_trigger TEXT DEFAULT 'all',
  time_of_day TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to cycles" ON cycles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to daily_logs" ON daily_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to reminders" ON reminders FOR ALL USING (true) WITH CHECK (true);
